### ISSUE TITLE
Add some important icons

### ISSUE THREAD

**Issue by phtdacosta** [mskocik/brackets-tree-icons#1]
First of all, I want to congratulate you for making this nice extension that should even come as default. I usually code in C, C++, Go, Dart, and even Processing (Arduino stuffs) and I really miss all these icons so I would ask you to add them in the incoming updates. Thanks! 👍

**Comment by mskocik** [comment]
Go and Arduino icons are still missing

**Comment by mskocik** [comment]
@phtdacosta what extension Processing (Arduino) has? I have no idea :)

**Comment by phtdacosta** [comment]
Hello @mskocik! Their files usually come with the two following extensions, both ".ino" and ".pde".
