### ISSUE TITLE
misaligned folders and files

### ISSUE THREAD

**Issue by vahid-sanati** [mskocik/brackets-tree-icons#2]
Hi. First of all your addon is so great and awesome. When I first used your addon I noticed that folders and files inside the same folder are not properly aligned and that is because of the arrow Icon beside folders. So I decided to make some modifications and remove the arrow icon of folders. You can see in the picture how properly are files and folders aligned now and the depth of opened folders is much more clear. 

![untitled](https://cloud.githubusercontent.com/assets/19893777/23547758/a86f6fa8-0019-11e7-9f13-e6b47c7fac5c.png)

I don't remember the details about the modifications but I have attached my modified version so you can see the changes and apply to your code if you want. (The file is a zip file but it was not accepting to upload the zip file so I changed the file extension to txt so it could be uploaded. Please rename the file extension to zip before extract)

[mskocik.brackets.icons.txt](https://github.com/mskocik/brackets-tree-icons/files/816505/mskocik.brackets.icons.txt)

Please note my modifications are for my own use and I have not published your code anywhere.

**Comment by mskocik** [comment]
Hi, you've reverted all changes I've done in latest updates:
- removing embedding font characters directly into file tree. Because it collided in a way [brackets-move-files](https://github.com/alemonteiro/brackets-move-files) extension works. 
- stripping font of unnecessary icons. 

If you feel like reworking it into proper pull-request I will merge it. Otherwise it will have to wait till I will have more time.

**Comment by vahid-sanati** [comment]
The changes are made in previous version that's why it doesn't have latest update changes. The main purpose that I show this to you is the idea of removing arrows beside folders to make files and folders correctly aligned. I don't use that move files extension so I'm ok with the version I currently have. Just wanted to show you how it looks if there is no arrow beside folders. thank you for your work.

**Comment by mskocik** [comment]
I understand your point. Will definitely look at it

**Comment by mskocik** [comment]
Thanks for your inspiration, I've updated extension accordingly and tweaked it further.

**Comment by vahid-sanati** [comment]
Glad I could help. Thank you for your work. The extension is perfect now.
